package com.bagpackers.agency.controller;

import com.bagpackers.agency.config.RateLimitingConfig;
import com.bagpackers.agency.model.AiIdpSandboxLog;
import com.bagpackers.agency.repository.AiIdpSandboxLogRepository;
import com.bagpackers.agency.exception.RateLimitExceededException;
import io.github.bucket4j.Bucket;
import jakarta.servlet.http.HttpServletRequest;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import java.security.MessageDigest;
import java.util.Map;
import java.util.UUID;

@RestController
@RequestMapping("/api/v1/sandbox/idp")
public class IdpSandboxController {

    private final RateLimitingConfig rateLimitingConfig;
    private final AiIdpSandboxLogRepository sandboxLogRepository;

    public IdpSandboxController(RateLimitingConfig rateLimitingConfig, AiIdpSandboxLogRepository sandboxLogRepository) {
        this.rateLimitingConfig = rateLimitingConfig;
        this.sandboxLogRepository = sandboxLogRepository;
    }

    @PostMapping
    public ResponseEntity<?> executeIdpSandbox(
            @Valid @RequestBody SandboxRequest payload,
            HttpServletRequest request
    ) {
        // Resolve rate limiting bucket
        String ipAddress = request.getRemoteAddr();
        Bucket bucket = rateLimitingConfig.resolveBucket(ipAddress);
        if (!bucket.tryConsume(1)) {
            throw new RateLimitExceededException("Rate limit exceeded. Max 10 requests/minute.");
        }


        String directoryStructure = payload.getContent();

        long startTime = System.currentTimeMillis();

        // OCR Directory-to-SQL logic Simulation
        String sql = generateSqlFromDirectory(directoryStructure);
        long executionTimeMs = System.currentTimeMillis() - startTime;

        // Generate MD5 hash of initial input
        String hash = getMd5Hash(directoryStructure);
        String sessionToken = payload.getSessionToken() != null ? payload.getSessionToken() : UUID.randomUUID().toString();

        AiIdpSandboxLog log = new AiIdpSandboxLog();
        log.setSessionToken(sessionToken);
        log.setInitialImageHash(hash);
        log.setGeneratedSql(sql);
        log.setExecutionTimeMs((int) executionTimeMs);

        try {
            sandboxLogRepository.save(log);
        } catch (Exception e) {
            // Silence DB save failures for sandbox robustness
        }

        return ResponseEntity.ok(Map.of(
            "sql", sql,
            "executionTimeMs", executionTimeMs,
            "hash", hash
        ));
    }

    private String generateSqlFromDirectory(String content) {
        // Simple directory to schema rules generator
        StringBuilder sb = new StringBuilder();
        sb.append("-- Dynamic SQL Schema generated by Intelligent Document Processing (IDP) OCR\n");
        sb.append("CREATE TABLE IF NOT EXISTS imported_records (\n");
        sb.append("    id SERIAL PRIMARY KEY,\n");

        boolean hasDate = content.toLowerCase().contains("date") || content.toLowerCase().contains("day");
        boolean hasPrice = content.toLowerCase().contains("price") || content.toLowerCase().contains("amount") || content.toLowerCase().contains("cost");
        boolean hasEmail = content.toLowerCase().contains("email") || content.toLowerCase().contains("mail");
        boolean hasQuantity = content.toLowerCase().contains("quantity") || content.toLowerCase().contains("qty");

        if (hasEmail) {
            sb.append("    email VARCHAR(255) UNIQUE NOT NULL,\n");
        }
        if (hasDate) {
            sb.append("    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n");
        }
        if (hasPrice) {
            sb.append("    amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,\n");
        }
        if (hasQuantity) {
            sb.append("    quantity INTEGER DEFAULT 1,\n");
        }

        sb.append("    raw_extracted_data TEXT,\n");
        sb.append("    processed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n");
        sb.append(");\n\n");

        sb.append("-- Indexes optimized for queries\n");
        if (hasEmail) {
            sb.append("CREATE INDEX IF NOT EXISTS idx_imported_records_email ON imported_records(email);\n");
        }
        if (hasDate) {
            sb.append("CREATE INDEX IF NOT EXISTS idx_imported_records_date ON imported_records(transaction_date DESC);\n");
        }

        return sb.toString();
    }

    private String getMd5Hash(String input) {
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            byte[] messageDigest = md.digest(input.getBytes());
            StringBuilder sb = new StringBuilder();
            for (byte b : messageDigest) {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        } catch (Exception e) {
            return "md5_hash_failed";
        }
    }

    public static class SandboxRequest {
        @NotBlank(message = "Directory contents cannot be empty.")
        private String content;

        private String sessionToken;

        public String getContent() {
            return content;
        }

        public void setContent(String content) {
            this.content = content;
        }

        public String getSessionToken() {
            return sessionToken;
        }

        public void setSessionToken(String sessionToken) {
            this.sessionToken = sessionToken;
        }
    }
}
