"use client";

import { useState } from "react";
import { Play, Copy, RefreshCw, AlertTriangle, Check, Terminal as TerminalIcon } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { escapeHtml } from "@/utils/security";
import { trackEvent } from "@/utils/telemetry";
import { runSandboxAction } from "@/app/actions";

const PRESETS = {
  invoices: `invoice_2026_01.pdf - Date: 2026-01-10, Amount: 1450.00, Email: customer@acme.com, Qty: 4
invoice_2026_02.pdf - Date: 2026-01-12, Amount: 980.50, Email: contact@globex.org, Qty: 2
invoice_2026_03.pdf - Date: 2026-01-15, Amount: 5600.00, Email: billing@cyberdyne.co, Qty: 10`,
  transactions: `order_6672 - Email: buyer@gmail.com, Total: 120.00, Date: 2026-02-01
order_6673 - Email: customer@yahoo.com, Total: 450.25, Date: 2026-02-02`,
  empty: `log_file.txt - Cost: 1200, Date: 2026-03-01`
};

export default function IdpSandbox() {
  const [content, setContent] = useState(PRESETS.invoices);
  const [loading, setLoading] = useState(false);
  const [sql, setSql] = useState("");
  const [stats, setStats] = useState<{ executionTimeMs: number; hash: string } | null>(null);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState("");

  const handlePreset = (key: keyof typeof PRESETS) => {
    setContent(PRESETS[key]);
    setError("");
  };

  const handleExecute = async () => {
    setLoading(true);
    setError("");
    setSql("");
    setStats(null);

    const sanitizedContent = escapeHtml(content);

    const result = await runSandboxAction(sanitizedContent, "showcase-session");
    
    if (result.success && result.data) {
      setSql(result.data.sql);
      setStats({
        executionTimeMs: result.data.executionTimeMs,
        hash: result.data.hash
      });
      trackEvent("sandbox_ocr_execute", {
        input_length: content.length,
        execution_success: true
      });
      setLoading(false);
    } else if (result.isOffline) {
      console.warn("Backend offline. Simulating local OCR execution.");
      setTimeout(() => {
        setSql(simulateSql(sanitizedContent));
        setStats({
          executionTimeMs: 42,
          hash: "a4f89d3c5e2193b2ef421b8c0de94b8e"
        });
        setLoading(false);
        trackEvent("sandbox_ocr_execute", {
          input_length: content.length,
          execution_success: true
        });
      }, 700);
    } else {
      setError(result.error || "Execution failed. Check backend console.");
      trackEvent("sandbox_ocr_execute", {
        input_length: content.length,
        execution_success: false
      });
      setLoading(false);
    }
  };

  const simulateSql = (input: string) => {
    const hasDate = input.toLowerCase().includes("date");
    const hasPrice = input.toLowerCase().includes("amount") || input.toLowerCase().includes("total") || input.toLowerCase().includes("cost");
    const hasEmail = input.toLowerCase().includes("email");
    const hasQty = input.toLowerCase().includes("qty");

    let sb = `-- Dynamic SQL Schema generated by Intelligent Document Processing (IDP) OCR (MOCK)\n`;
    sb += `CREATE TABLE IF NOT EXISTS imported_records (\n`;
    sb += `    id SERIAL PRIMARY KEY,\n`;
    if (hasEmail) sb += `    email VARCHAR(255) UNIQUE NOT NULL,\n`;
    if (hasDate) sb += `    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n`;
    if (hasPrice) sb += `    amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,\n`;
    if (hasQty) sb += `    quantity INTEGER DEFAULT 1,\n`;
    sb += `    raw_extracted_data TEXT,\n`;
    sb += `    processed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n`;
    sb += `);\n\n`;

    sb += `-- Indexes optimized for queries\n`;
    if (hasEmail) sb += `CREATE INDEX IF NOT EXISTS idx_imported_records_email ON imported_records(email);\n`;
    if (hasDate) sb += `CREATE INDEX IF NOT EXISTS idx_imported_records_date ON imported_records(transaction_date DESC);\n`;

    return sb;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(sql);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <motion.div 
      initial={{ opacity: 0, y: 30 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-100px" }}
      transition={{ duration: 0.6, ease: "easeOut" }}
      className="w-full max-w-5xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-8 items-stretch"
    >
      {/* Input panel */}
      <div className="bg-[#18181B] rounded-2xl p-6 border border-[#27272A] flex flex-col justify-between shadow-xl">
        <div>
          <div className="flex justify-between items-center mb-4">
            <h4 className="font-bold text-white flex items-center gap-2">
              <TerminalIcon size={16} className="text-[#3B82F6]" />
              OCR Document Input
            </h4>
            <div className="flex gap-2">
              {(["invoices", "transactions", "empty"] as const).map((preset) => (
                <motion.button
                  key={preset}
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  onClick={() => handlePreset(preset)}
                  className="text-[10px] bg-[#27272A] hover:bg-[#475569] border border-[#475569] hover:border-[#3B82F6]/40 text-[#E2E8F0] hover:text-white px-2.5 py-1.5 rounded transition-all cursor-pointer"
                >
                  {preset.charAt(0).toUpperCase() + preset.slice(1)}
                </motion.button>
              ))}
            </div>
          </div>
          <p className="text-xs text-[#CBD5E1] mb-4 leading-relaxed">
            Enter directory document OCR outputs, scan logs, or CSV structures below to auto-synthesize indexes and relations.
          </p>
          <textarea
            value={content}
            onChange={(e) => setContent(e.target.value)}
            className="w-full h-64 bg-[#09090B] border border-[#27272A] focus:border-[#3B82F6]/50 rounded-xl p-4 text-xs font-mono text-gray-300 focus:outline-none focus:ring-1 focus:ring-[#3B82F6] transition-all"
            placeholder="Paste text contents here..."
          />
        </div>

        <motion.button
          whileHover={{ scale: 1.01 }}
          whileTap={{ scale: 0.99 }}
          onClick={handleExecute}
          disabled={loading}
          className="w-full mt-6 inline-flex items-center justify-center gap-2 px-5 py-3 rounded-lg bg-[#3B82F6] hover:bg-[#2563EB] text-white font-semibold text-sm transition-all active:scale-[0.98] disabled:opacity-50 cursor-pointer shadow-md shadow-black/20"
        >
          {loading ? (
            <RefreshCw size={16} className="animate-spin" />
          ) : (
            <Play size={16} />
          )}
          {loading ? "Processing Document Schema..." : "Execute IDP Extraction Pipeline"}
        </motion.button>
      </div>

      {/* Output Panel */}
      <div className="bg-[#18181B] rounded-2xl p-6 border border-[#27272A] flex flex-col justify-between min-h-[400px] shadow-xl">
        <div className="flex-1 flex flex-col justify-between">
          <div className="flex justify-between items-center mb-4">
            <h4 className="font-bold text-white flex items-center gap-2">
              <span className="w-2.5 h-2.5 rounded-full bg-[#10B891] animate-pulse" />
              Synthesized SQL Schema
            </h4>
            {sql && (
              <motion.button
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                onClick={handleCopy}
                className="text-xs flex items-center gap-1.5 text-gray-300 hover:text-white transition-colors cursor-pointer"
              >
                {copied ? <Check size={12} className="text-[#10B891]" /> : <Copy size={12} />}
                {copied ? "Copied" : "Copy SQL"}
              </motion.button>
            )}
          </div>

          <AnimatePresence mode="wait">
            {error && (
              <motion.div 
                initial={{ opacity: 0, scale: 0.98 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0 }}
                className="alert-danger p-4 rounded-lg flex items-start gap-2.5 text-xs my-auto"
              >
                <AlertTriangle size={16} className="shrink-0 animate-bounce" />
                <div>
                  <span className="font-bold font-sans">Rate limit active:</span> {error}
                </div>
              </motion.div>
            )}

            {!error && !sql && !loading && (
              <motion.div 
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="flex-1 flex flex-col items-center justify-center text-center py-12 text-gray-400 border border-dashed border-[#27272A] rounded-xl bg-black/10"
              >
                <TerminalIcon size={32} className="mb-2 opacity-40 text-[#3B82F6]" />
                <span className="text-xs font-sans">Awaiting execution. Select a preset and run the pipeline.</span>
              </motion.div>
            )}

            {loading && (
              <motion.div 
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="flex-1 flex flex-col items-center justify-center py-12 text-gray-300"
              >
                <RefreshCw size={24} className="animate-spin text-[#3B82F6] mb-2" />
                <span className="text-xs font-sans">Running OCR scanner & database normalizers...</span>
              </motion.div>
            )}

            {!error && sql && (
              <motion.div 
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0 }}
                className="flex-1 flex flex-col justify-between"
              >
                <pre className="p-4 bg-[#09090B] border border-[#27272A] rounded-xl text-xs font-mono text-[#60A5FA] overflow-x-auto max-h-[300px] select-all whitespace-pre">
                  {sql}
                </pre>

                {stats && (
                  <motion.div 
                    initial={{ scale: 0.95, opacity: 0 }}
                    animate={{ scale: 1, opacity: 1 }}
                    className="alert-success mt-4 p-3 rounded-lg flex justify-between items-center text-[10px] uppercase tracking-wider font-bold"
                  >
                    <div>
                      Success: Extraction finalized in <span className="font-mono font-black text-[#10B891]">{stats.executionTimeMs}ms</span>
                    </div>
                    <div className="font-mono lowercase text-gray-400">
                      {stats.hash.slice(0, 10)}
                    </div>
                  </motion.div>
                )}
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </motion.div>
  );
}
